title: "My Awesome Coursera Site!"
description: "This is the description of my awesome site." 
baseurl: "/coursera-test/"
url: https://mrojo1269.github.io/coursera-test/
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
