# This is to configure the theme for my coursera test webpage
theme: jekyll-theme-primer
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Hello Coursera!</title>
</head>
<body>
<h1>Hello Coursera! It's a great course!</h1>
</body>
</html>