title: "My Awesome Coursera Site!"
description: "This is the description of my awesome site." 
baseurl: "/coursera-test/site"
url: https://mrojo1269.github.io/coursera-test/site/
theme: jekyll-theme-primer
